# Generated by Django 5.1.6 on 2025-02-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('club_type', models.CharField(choices=[('제1동아리', '제1동아리'), ('제2동아리', '제2동아리'), ('자율동아리', '자율동아리')], max_length=20)),
                ('description', models.TextField()),
                ('leader', models.CharField(max_length=50)),
                ('poster', models.ImageField(upload_to='club_posters/')),
            ],
        ),
    ]
