# Generated by Django 5.1.6 on 2025-02-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
