# Generated by Django 5.1.6 on 2025-02-19 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
