# Generated by Django 5.1.6 on 2025-02-19 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10, unique=True, verbose_name='학번')),
                ('is_leader', models.BooleanField(default=False, verbose_name='기장 여부')),
                ('first_choice_club1', models.CharField(blank=True, max_length=100, null=True, verbose_name='1지망 제1동아리')),
                ('first_choice_club1_status', models.CharField(choices=[('true', '합격'), ('false', '불합격'), ('none', '미정')], default='none', max_length=10)),
                ('second_choice_club1', models.CharField(blank=True, max_length=100, null=True, verbose_name='2지망 제1동아리')),
                ('second_choice_club1_status', models.CharField(choices=[('true', '합격'), ('false', '불합격'), ('none', '미정')], default='none', max_length=10)),
                ('first_choice_club2', models.CharField(blank=True, max_length=100, null=True, verbose_name='1지망 제2동아리')),
                ('first_choice_club2_status', models.CharField(choices=[('true', '합격'), ('false', '불합격'), ('none', '미정')], default='none', max_length=10)),
                ('second_choice_club2', models.CharField(blank=True, max_length=100, null=True, verbose_name='2지망 제2동아리')),
                ('second_choice_club2_status', models.CharField(choices=[('true', '합격'), ('false', '불합격'), ('none', '미정')], default='none', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
